// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TripPlanner.Api.Data;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TripPlanner.Api.Domain.Chat.ChatMessage", b =>
                {
                    b.Property<Guid>("ChatMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SentByEventMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("ChatMessageId");

                    b.HasIndex("ChatRoomId");

                    b.HasIndex("SentByEventMemberId");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Chat.ChatRoom", b =>
                {
                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.HasKey("ChatRoomId");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("ChatRooms", (string)null);
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Events.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<double>("DestinationLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("DestinationLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<bool>("IsJoinEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocationSharingActive")
                        .HasColumnType("boolean");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("JoinPasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("LocationShareScope")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OwnerOrganizerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PassiveAllowedCapabilities")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("EventId");

                    b.HasIndex("JoinCode")
                        .IsUnique();

                    b.HasIndex("OwnerOrganizerId");

                    b.ToTable("Events", null, t =>
                        {
                            t.HasCheckConstraint("CK_Events_DateRange", "\"EndDate\" IS NULL OR \"EndDate\" >= \"StartDate\"");
                        });
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Events.EventMember", b =>
                {
                    b.Property<Guid>("EventMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MemberType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("EventMemberId");

                    b.HasIndex("UserId");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique();

                    b.ToTable("EventMembers", (string)null);

                    b.HasDiscriminator<string>("MemberType").HasValue("EventMember");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Location.LocationPoint", b =>
                {
                    b.Property<Guid>("LocationPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Accuracy")
                        .HasColumnType("double precision");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<Guid>("LocationSessionId")
                        .HasColumnType("uuid");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LocationPointId");

                    b.HasIndex("LocationSessionId");

                    b.ToTable("LocationPoints");
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Location.LocationSession", b =>
                {
                    b.Property<Guid>("LocationSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventMemberId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LocationSessionId");

                    b.HasIndex("EventMemberId")
                        .IsUnique();

                    b.ToTable("LocationSessions");
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Media.EventMedia", b =>
                {
                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedByEventMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("MediaId");

                    b.HasIndex("EventId");

                    b.HasIndex("UploadedByEventMemberId");

                    b.ToTable("EventMedia", (string)null);
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Schedule.Activity", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<int>("ActivityOrder")
                        .HasColumnType("integer");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventDayId")
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("ActivityId");

                    b.HasIndex("EventDayId");

                    b.ToTable("Activities", null, t =>
                        {
                            t.HasCheckConstraint("CK_Activities_TimeRange", "\"StartTime\" IS NULL OR \"EndTime\" IS NULL OR \"EndTime\" >= \"StartTime\"");
                        });
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Schedule.ActivityStep", b =>
                {
                    b.Property<Guid>("ActivityStepId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.HasKey("ActivityStepId");

                    b.HasIndex("ActivityId");

                    b.ToTable("ActivitySteps", (string)null);
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Schedule.EventDay", b =>
                {
                    b.Property<Guid>("EventDayId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("EventDayId");

                    b.HasIndex("EventId");

                    b.ToTable("EventDays", (string)null);
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Users.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("EmailVerificationCodeHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmailVerificationExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Voice.VoiceChannel", b =>
                {
                    b.Property<Guid>("VoiceChannelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("VoiceChannelId");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("VoiceChannels", (string)null);
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Voice.VoiceRecording", b =>
                {
                    b.Property<Guid>("VoiceRecordingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("VoiceSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("VoiceRecordingId");

                    b.HasIndex("VoiceSessionId");

                    b.ToTable("VoiceRecordings", (string)null);
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Voice.VoiceSession", b =>
                {
                    b.Property<Guid>("VoiceSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRecorded")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StartedByEventMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VoiceChannelId")
                        .HasColumnType("uuid");

                    b.HasKey("VoiceSessionId");

                    b.HasIndex("StartedByEventMemberId");

                    b.HasIndex("VoiceChannelId");

                    b.ToTable("VoiceSessions", (string)null);
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Events.Organizer", b =>
                {
                    b.HasBaseType("TripPlanner.Api.Domain.Events.EventMember");

                    b.Property<string>("DisplayTitle")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasDiscriminator().HasValue("Organizer");
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Events.Participant", b =>
                {
                    b.HasBaseType("TripPlanner.Api.Domain.Events.EventMember");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Participant");
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Chat.ChatMessage", b =>
                {
                    b.HasOne("TripPlanner.Api.Domain.Chat.ChatRoom", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripPlanner.Api.Domain.Events.EventMember", null)
                        .WithMany()
                        .HasForeignKey("SentByEventMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Chat.ChatRoom", b =>
                {
                    b.HasOne("TripPlanner.Api.Domain.Events.Event", null)
                        .WithOne("ChatRoom")
                        .HasForeignKey("TripPlanner.Api.Domain.Chat.ChatRoom", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Events.Event", b =>
                {
                    b.HasOne("TripPlanner.Api.Domain.Events.EventMember", null)
                        .WithMany()
                        .HasForeignKey("OwnerOrganizerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("TripPlanner.Api.Domain.Events.LocationGrant", "LocationGrants", b1 =>
                        {
                            b1.Property<Guid>("LocationGrantId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("EventId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("GrantedByMemberId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("GrantedToMemberId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean");

                            b1.HasKey("LocationGrantId");

                            b1.HasIndex("GrantedByMemberId");

                            b1.HasIndex("GrantedToMemberId");

                            b1.HasIndex("EventId", "GrantedByMemberId", "GrantedToMemberId")
                                .IsUnique();

                            b1.ToTable("EventLocationGrants", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EventId");

                            b1.HasOne("TripPlanner.Api.Domain.Events.EventMember", null)
                                .WithMany()
                                .HasForeignKey("GrantedByMemberId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.HasOne("TripPlanner.Api.Domain.Events.EventMember", null)
                                .WithMany()
                                .HasForeignKey("GrantedToMemberId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.Navigation("LocationGrants");
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Events.EventMember", b =>
                {
                    b.HasOne("TripPlanner.Api.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Location.LocationPoint", b =>
                {
                    b.HasOne("TripPlanner.Api.Domain.Location.LocationSession", null)
                        .WithMany("Points")
                        .HasForeignKey("LocationSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Location.LocationSession", b =>
                {
                    b.HasOne("TripPlanner.Api.Domain.Events.EventMember", null)
                        .WithOne("LocationSession")
                        .HasForeignKey("TripPlanner.Api.Domain.Location.LocationSession", "EventMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Media.EventMedia", b =>
                {
                    b.HasOne("TripPlanner.Api.Domain.Events.Event", null)
                        .WithMany("EventMedia")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripPlanner.Api.Domain.Events.EventMember", null)
                        .WithMany()
                        .HasForeignKey("UploadedByEventMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Schedule.Activity", b =>
                {
                    b.HasOne("TripPlanner.Api.Domain.Schedule.EventDay", null)
                        .WithMany("Activities")
                        .HasForeignKey("EventDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Schedule.ActivityStep", b =>
                {
                    b.HasOne("TripPlanner.Api.Domain.Schedule.Activity", null)
                        .WithMany("Steps")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Schedule.EventDay", b =>
                {
                    b.HasOne("TripPlanner.Api.Domain.Events.Event", null)
                        .WithMany("EventDays")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Users.RefreshToken", b =>
                {
                    b.HasOne("TripPlanner.Api.Domain.Users.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Voice.VoiceChannel", b =>
                {
                    b.HasOne("TripPlanner.Api.Domain.Events.Event", null)
                        .WithOne("VoiceChannel")
                        .HasForeignKey("TripPlanner.Api.Domain.Voice.VoiceChannel", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Voice.VoiceRecording", b =>
                {
                    b.HasOne("TripPlanner.Api.Domain.Voice.VoiceSession", null)
                        .WithMany("Recordings")
                        .HasForeignKey("VoiceSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Voice.VoiceSession", b =>
                {
                    b.HasOne("TripPlanner.Api.Domain.Events.EventMember", null)
                        .WithMany()
                        .HasForeignKey("StartedByEventMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TripPlanner.Api.Domain.Voice.VoiceChannel", null)
                        .WithMany("Sessions")
                        .HasForeignKey("VoiceChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Events.Organizer", b =>
                {
                    b.HasOne("TripPlanner.Api.Domain.Events.Event", null)
                        .WithMany("Organizers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Events.Participant", b =>
                {
                    b.HasOne("TripPlanner.Api.Domain.Events.Event", null)
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Chat.ChatRoom", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Events.Event", b =>
                {
                    b.Navigation("ChatRoom")
                        .IsRequired();

                    b.Navigation("EventDays");

                    b.Navigation("EventMedia");

                    b.Navigation("Organizers");

                    b.Navigation("Participants");

                    b.Navigation("VoiceChannel")
                        .IsRequired();
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Events.EventMember", b =>
                {
                    b.Navigation("LocationSession");
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Location.LocationSession", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Schedule.Activity", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Schedule.EventDay", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Users.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Voice.VoiceChannel", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("TripPlanner.Api.Domain.Voice.VoiceSession", b =>
                {
                    b.Navigation("Recordings");
                });
#pragma warning restore 612, 618
        }
    }
}
