using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using TripPlanner.Api.Domain;
using TripPlanner.Api.Domain.Chat;
using TripPlanner.Api.Domain.Events;
using TripPlanner.Api.Domain.Location;
using TripPlanner.Api.Domain.Media;
using TripPlanner.Api.Domain.Schedule;
using TripPlanner.Api.Domain.Users;
using TripPlanner.Api.Domain.Voice;

namespace TripPlanner.Api.Data;

public static class ModelMap
{
    public static void Apply(ModelBuilder modelBuilder)
    {
        // -------------------------------------------------------
        // GUIDs generated by application (DDD aggregate style)
        // -------------------------------------------------------
        
        modelBuilder.Entity<User>()
            .Property(x => x.UserId)
            .ValueGeneratedNever();

        modelBuilder.Entity<Event>()
            .Property(x => x.EventId)
            .ValueGeneratedNever();

        modelBuilder.Entity<EventMember>()
            .Property(x => x.EventMemberId)
            .ValueGeneratedNever();

        modelBuilder.Entity<ChatRoom>()
            .Property(x => x.ChatRoomId)
            .ValueGeneratedNever();

        modelBuilder.Entity<ChatMessage>()
            .Property(x => x.ChatMessageId)
            .ValueGeneratedNever();

        modelBuilder.Entity<VoiceChannel>()
            .Property(x => x.VoiceChannelId)
            .ValueGeneratedNever();

        modelBuilder.Entity<VoiceSession>()
            .Property(x => x.VoiceSessionId)
            .ValueGeneratedNever();

        modelBuilder.Entity<VoiceRecording>()
            .Property(x => x.VoiceRecordingId)
            .ValueGeneratedNever();

        modelBuilder.Entity<EventDay>()
            .Property(x => x.EventDayId)
            .ValueGeneratedNever();

        modelBuilder.Entity<Activity>()
            .Property(x => x.ActivityId)
            .ValueGeneratedNever();

        modelBuilder.Entity<ActivityStep>()
            .Property(x => x.ActivityStepId)
            .ValueGeneratedNever();

        modelBuilder.Entity<EventMedia>()
            .Property(x => x.MediaId)
            .ValueGeneratedNever();

        modelBuilder.Entity<RefreshToken>()
            .Property(x => x.RefreshTokenId)
            .ValueGeneratedNever();

        // -------------------------------------------------------
        // Users
        // -------------------------------------------------------

        modelBuilder.Entity<User>(b =>
        {
            b.ToTable("Users");
            b.HasIndex(x => x.Email).IsUnique();
        });

        // -------------------------------------------------------
        // RefreshTokens
        // -------------------------------------------------------

        modelBuilder.Entity<RefreshToken>(b =>
        {
            b.ToTable("RefreshTokens");
            b.HasIndex(x => x.TokenHash).IsUnique();

            b.HasOne(x => x.User)
                .WithMany(u => u.RefreshTokens)
                .HasForeignKey(x => x.UserId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        // -------------------------------------------------------
        // EventMembers (TPH)
        // -------------------------------------------------------

        modelBuilder.Entity<EventMember>(b =>
        {
            b.ToTable("EventMembers");

            b.HasDiscriminator<string>("MemberType")
                .HasValue<Organizer>("Organizer")
                .HasValue<Participant>("Participant");

            b.HasIndex(x => new { x.EventId, x.UserId }).IsUnique();
            b.HasIndex(x => new { x.UserId, x.Status });

            b.HasOne<User>()
                .WithMany()
                .HasForeignKey(m => m.UserId)
                .OnDelete(DeleteBehavior.Restrict);
        });

        // -------------------------------------------------------
        // Events
        // -------------------------------------------------------

        modelBuilder.Entity<Event>(b =>
        {
            b.ToTable("Events");

            b.HasMany(e => e.Organizers)
                .WithOne()
                .HasForeignKey(o => o.EventId)
                .OnDelete(DeleteBehavior.Cascade);

            b.HasMany(e => e.Participants)
                .WithOne()
                .HasForeignKey(p => p.EventId)
                .OnDelete(DeleteBehavior.Cascade);

            b.HasCheckConstraint(
                "CK_Events_DateRange",
                "[EndDate] IS NULL OR [EndDate] >= [StartDate]"
            );

            b.HasIndex(e => e.JoinCode).IsUnique();

            b.HasOne(e => e.ChatRoom)
                .WithOne()
                .HasForeignKey<ChatRoom>(cr => cr.EventId)
                .OnDelete(DeleteBehavior.Cascade);

            b.HasOne(e => e.VoiceChannel)
                .WithOne()
                .HasForeignKey<VoiceChannel>(vc => vc.EventId)
                .OnDelete(DeleteBehavior.Cascade);

            b.Property(e => e.PassiveAllowedCapabilities)
                .HasConversion(
                    v => JsonSerializer.Serialize(v, (JsonSerializerOptions?)null),
                    v => JsonSerializer.Deserialize<HashSet<Capability>>(v, (JsonSerializerOptions?)null) ?? new HashSet<Capability>()
                )
                .HasColumnType("nvarchar(max)")
                .IsRequired();

            b.HasOne<EventMember>()
                .WithMany()
                .HasForeignKey(e => e.OwnerOrganizerId)
                .IsRequired(false)
                .OnDelete(DeleteBehavior.Restrict);

            b.OwnsMany(e => e.LocationGrants, og =>
            {
                og.ToTable("EventLocationGrants");

                og.WithOwner().HasForeignKey("EventId");

                og.Property(x => x.LocationGrantId).ValueGeneratedNever();

                og.HasKey(x => x.LocationGrantId);

                og.Property(x => x.GrantedByMemberId).IsRequired();
                og.Property(x => x.GrantedToMemberId).IsRequired();
                og.Property(x => x.CreatedAt).IsRequired();
                og.Property(x => x.IsActive).IsRequired();

                og.HasIndex("EventId", nameof(LocationGrant.GrantedByMemberId), nameof(LocationGrant.GrantedToMemberId))
                    .IsUnique();

                og.HasOne<EventMember>()
                    .WithMany()
                    .HasForeignKey(x => x.GrantedByMemberId)
                    .OnDelete(DeleteBehavior.Restrict);

                og.HasOne<EventMember>()
                    .WithMany()
                    .HasForeignKey(x => x.GrantedToMemberId)
                    .OnDelete(DeleteBehavior.Restrict);
            });
        });

        // -------------------------------------------------------
        // Chat
        // -------------------------------------------------------

        modelBuilder.Entity<ChatRoom>().ToTable("ChatRooms");

        modelBuilder.Entity<ChatMessage>(b =>
        {
            b.ToTable("ChatMessages");

            b.HasOne<EventMember>()
                .WithMany()
                .HasForeignKey(m => m.SentByEventMemberId)
                .OnDelete(DeleteBehavior.Restrict);
        });

        // -------------------------------------------------------
        // Voice
        // -------------------------------------------------------

        modelBuilder.Entity<VoiceChannel>().ToTable("VoiceChannels");

        modelBuilder.Entity<VoiceSession>(b =>
        {
            b.ToTable("VoiceSessions");

            b.HasOne<EventMember>()
                .WithMany()
                .HasForeignKey(s => s.StartedByEventMemberId)
                .OnDelete(DeleteBehavior.Restrict);
        });

        modelBuilder.Entity<VoiceRecording>().ToTable("VoiceRecordings");

        // -------------------------------------------------------
        // Schedule
        // -------------------------------------------------------

        modelBuilder.Entity<EventDay>(b =>
        {
            b.ToTable("EventDays");
            b.HasIndex(x => new { x.EventId, x.Date, x.DayOrder });
        });

        modelBuilder.Entity<Activity>(b =>
        {
            b.ToTable("Activities");
            b.HasIndex(x => new { x.EventDayId, x.ActivityOrder });

            b.HasCheckConstraint(
                "CK_Activities_TimeRange",
                "[StartTime] IS NULL OR [EndTime] IS NULL OR [EndTime] >= [StartTime]"
            );
        });

        modelBuilder.Entity<ActivityStep>().ToTable("ActivitySteps");

        // -------------------------------------------------------
        // Location
        // -------------------------------------------------------

        modelBuilder.Entity<LocationSession>(b =>
        {
            b.ToTable("LocationSessions");
            b.HasIndex(x => x.EventMemberId).IsUnique();
        });

        modelBuilder.Entity<LocationPoint>(b =>
        {
            b.ToTable("LocationPoints");
            b.HasIndex(x => new { x.LocationSessionId, x.RecordedAt });
        });

        // -------------------------------------------------------
        // Media
        // -------------------------------------------------------

        modelBuilder.Entity<EventMedia>(b =>
        {
            b.ToTable("EventMedia");

            b.HasOne<Event>()
                .WithMany(e => e.EventMedia)
                .HasForeignKey(m => m.EventId)
                .OnDelete(DeleteBehavior.Cascade);

            b.HasOne<EventMember>()
                .WithMany()
                .HasForeignKey(m => m.UploadedByEventMemberId)
                .OnDelete(DeleteBehavior.Restrict);
        });
    }
}
